name: smartwarrior
favicon: null
layout_spectrum: 0
typography_spectrum: 0.25165
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4f4f4'
    - '#1e0000'
    - '#ee0000'
    - '#f15a25'
    - '#836868'
  brandStrength: 1
  lightness: 0.75
  saturation: 1
  rhythmicContrast: 0.5
purpose:
  - name: engagement
    item: 4591b423-44e0-4e1b-b648-2bdde9a8f195
    url: null
